project               = "doubleday"
environment           = "prod"
region                = "us-east-1"
athena_results_bucket = "appleforge-athena-query-results"
powertools_layer_arn  = "arn:aws:lambda:us-east-1:017000801446:layer:AWSLambdaPowertoolsPythonV3-python312-x86_64:15"
