project               = "doubleday"
environment           = "prod"
region                = "us-east-1"
athena_results_bucket = "appleforge-athena-query-results"
powertools_layer_arn  = "arn:aws:lambda:us-east-1:017000801446:layer:AWSLambdaPowertoolsPythonV3-python312-x86_64:15"
api_domain_name       = "api.doubleday.appleforge.com"
frontend_domain_name  = "doubleday.appleforge.com"
hosted_zone_name      = "appleforge.com"
cognito_callback_urls = ["https://doubleday.appleforge.com/callback", "doubleday://callback"]
cognito_logout_urls   = ["https://doubleday.appleforge.com", "doubleday://"]
enable_stripe = false
