MERGE INTO silver_pitches AS t
USING silver_pitches_staging AS s
ON t.game_pk = s.game_pk
  AND t.at_bat_number = s.at_bat_number
  AND t.pitch_number = s.pitch_number
  AND t.season = s.season
  AND t.game_date = s.game_date
WHEN MATCHED THEN UPDATE SET
  game_type = s.game_type,
  game_year = s.game_year,
  home_team = s.home_team,
  away_team = s.away_team,
  inning = s.inning,
  inning_topbot = s.inning_topbot,
  outs_when_up = s.outs_when_up,
  balls = s.balls,
  strikes = s.strikes,
  batter = s.batter,
  pitcher = s.pitcher,
  player_name = s.player_name,
  stand = s.stand,
  p_throws = s.p_throws,
  on_1b = s.on_1b,
  on_2b = s.on_2b,
  on_3b = s.on_3b,
  fielder_2 = s.fielder_2,
  fielder_3 = s.fielder_3,
  fielder_4 = s.fielder_4,
  fielder_5 = s.fielder_5,
  fielder_6 = s.fielder_6,
  fielder_7 = s.fielder_7,
  fielder_8 = s.fielder_8,
  fielder_9 = s.fielder_9,
  pitch_type = s.pitch_type,
  pitch_name = s.pitch_name,
  type = s.type,
  events = s.events,
  description = s.description,
  des = s.des,
  zone = s.zone,
  hit_location = s.hit_location,
  bb_type = s.bb_type,
  release_speed = s.release_speed,
  effective_speed = s.effective_speed,
  release_spin_rate = s.release_spin_rate,
  spin_dir = s.spin_dir,
  spin_axis = s.spin_axis,
  release_pos_x = s.release_pos_x,
  release_pos_y = s.release_pos_y,
  release_pos_z = s.release_pos_z,
  release_extension = s.release_extension,
  pfx_x = s.pfx_x,
  pfx_z = s.pfx_z,
  plate_x = s.plate_x,
  plate_z = s.plate_z,
  vx0 = s.vx0,
  vy0 = s.vy0,
  vz0 = s.vz0,
  ax = s.ax,
  ay = s.ay,
  az = s.az,
  sz_top = s.sz_top,
  sz_bot = s.sz_bot,
  api_break_z_with_gravity = s.api_break_z_with_gravity,
  api_break_x_arm = s.api_break_x_arm,
  api_break_x_batter_in = s.api_break_x_batter_in,
  arm_angle = s.arm_angle,
  launch_speed = s.launch_speed,
  launch_angle = s.launch_angle,
  launch_speed_angle = s.launch_speed_angle,
  hit_distance_sc = s.hit_distance_sc,
  hc_x = s.hc_x,
  hc_y = s.hc_y,
  bat_speed = s.bat_speed,
  swing_length = s.swing_length,
  hyper_speed = s.hyper_speed,
  attack_angle = s.attack_angle,
  attack_direction = s.attack_direction,
  swing_path_tilt = s.swing_path_tilt,
  intercept_ball_minus_batter_pos_x_inches = s.intercept_ball_minus_batter_pos_x_inches,
  intercept_ball_minus_batter_pos_y_inches = s.intercept_ball_minus_batter_pos_y_inches,
  home_score = s.home_score,
  away_score = s.away_score,
  bat_score = s.bat_score,
  fld_score = s.fld_score,
  post_home_score = s.post_home_score,
  post_away_score = s.post_away_score,
  post_bat_score = s.post_bat_score,
  post_fld_score = s.post_fld_score,
  home_score_diff = s.home_score_diff,
  bat_score_diff = s.bat_score_diff,
  estimated_ba_using_speedangle = s.estimated_ba_using_speedangle,
  estimated_woba_using_speedangle = s.estimated_woba_using_speedangle,
  estimated_slg_using_speedangle = s.estimated_slg_using_speedangle,
  woba_value = s.woba_value,
  woba_denom = s.woba_denom,
  babip_value = s.babip_value,
  iso_value = s.iso_value,
  home_win_exp = s.home_win_exp,
  bat_win_exp = s.bat_win_exp,
  delta_home_win_exp = s.delta_home_win_exp,
  delta_run_exp = s.delta_run_exp,
  delta_pitcher_run_exp = s.delta_pitcher_run_exp,
  if_fielding_alignment = s.if_fielding_alignment,
  of_fielding_alignment = s.of_fielding_alignment,
  age_pit = s.age_pit,
  age_bat = s.age_bat,
  age_pit_legacy = s.age_pit_legacy,
  age_bat_legacy = s.age_bat_legacy,
  n_thruorder_pitcher = s.n_thruorder_pitcher,
  n_priorpa_thisgame_player_at_bat = s.n_priorpa_thisgame_player_at_bat,
  pitcher_days_since_prev_game = s.pitcher_days_since_prev_game,
  batter_days_since_prev_game = s.batter_days_since_prev_game,
  pitcher_days_until_next_game = s.pitcher_days_until_next_game,
  batter_days_until_next_game = s.batter_days_until_next_game,
  umpire = s.umpire,
  sv_id = s.sv_id
WHEN NOT MATCHED THEN INSERT (
  game_pk, at_bat_number, pitch_number,
  game_type, game_year, home_team, away_team, inning, inning_topbot,
  outs_when_up, balls, strikes,
  batter, pitcher, player_name, stand, p_throws,
  on_1b, on_2b, on_3b,
  fielder_2, fielder_3, fielder_4, fielder_5, fielder_6, fielder_7, fielder_8, fielder_9,
  pitch_type, pitch_name, type, events, description, des, zone, hit_location, bb_type,
  release_speed, effective_speed, release_spin_rate, spin_dir, spin_axis,
  release_pos_x, release_pos_y, release_pos_z, release_extension,
  pfx_x, pfx_z, plate_x, plate_z,
  vx0, vy0, vz0, ax, ay, az,
  sz_top, sz_bot,
  api_break_z_with_gravity, api_break_x_arm, api_break_x_batter_in, arm_angle,
  launch_speed, launch_angle, launch_speed_angle, hit_distance_sc,
  hc_x, hc_y, bat_speed, swing_length, hyper_speed,
  attack_angle, attack_direction, swing_path_tilt,
  intercept_ball_minus_batter_pos_x_inches, intercept_ball_minus_batter_pos_y_inches,
  home_score, away_score, bat_score, fld_score,
  post_home_score, post_away_score, post_bat_score, post_fld_score,
  home_score_diff, bat_score_diff,
  estimated_ba_using_speedangle, estimated_woba_using_speedangle, estimated_slg_using_speedangle,
  woba_value, woba_denom, babip_value, iso_value,
  home_win_exp, bat_win_exp, delta_home_win_exp, delta_run_exp, delta_pitcher_run_exp,
  if_fielding_alignment, of_fielding_alignment,
  age_pit, age_bat, age_pit_legacy, age_bat_legacy,
  n_thruorder_pitcher, n_priorpa_thisgame_player_at_bat,
  pitcher_days_since_prev_game, batter_days_since_prev_game,
  pitcher_days_until_next_game, batter_days_until_next_game,
  umpire, sv_id,
  season, game_date
) VALUES (
  s.game_pk, s.at_bat_number, s.pitch_number,
  s.game_type, s.game_year, s.home_team, s.away_team, s.inning, s.inning_topbot,
  s.outs_when_up, s.balls, s.strikes,
  s.batter, s.pitcher, s.player_name, s.stand, s.p_throws,
  s.on_1b, s.on_2b, s.on_3b,
  s.fielder_2, s.fielder_3, s.fielder_4, s.fielder_5, s.fielder_6, s.fielder_7, s.fielder_8, s.fielder_9,
  s.pitch_type, s.pitch_name, s.type, s.events, s.description, s.des, s.zone, s.hit_location, s.bb_type,
  s.release_speed, s.effective_speed, s.release_spin_rate, s.spin_dir, s.spin_axis,
  s.release_pos_x, s.release_pos_y, s.release_pos_z, s.release_extension,
  s.pfx_x, s.pfx_z, s.plate_x, s.plate_z,
  s.vx0, s.vy0, s.vz0, s.ax, s.ay, s.az,
  s.sz_top, s.sz_bot,
  s.api_break_z_with_gravity, s.api_break_x_arm, s.api_break_x_batter_in, s.arm_angle,
  s.launch_speed, s.launch_angle, s.launch_speed_angle, s.hit_distance_sc,
  s.hc_x, s.hc_y, s.bat_speed, s.swing_length, s.hyper_speed,
  s.attack_angle, s.attack_direction, s.swing_path_tilt,
  s.intercept_ball_minus_batter_pos_x_inches, s.intercept_ball_minus_batter_pos_y_inches,
  s.home_score, s.away_score, s.bat_score, s.fld_score,
  s.post_home_score, s.post_away_score, s.post_bat_score, s.post_fld_score,
  s.home_score_diff, s.bat_score_diff,
  s.estimated_ba_using_speedangle, s.estimated_woba_using_speedangle, s.estimated_slg_using_speedangle,
  s.woba_value, s.woba_denom, s.babip_value, s.iso_value,
  s.home_win_exp, s.bat_win_exp, s.delta_home_win_exp, s.delta_run_exp, s.delta_pitcher_run_exp,
  s.if_fielding_alignment, s.of_fielding_alignment,
  s.age_pit, s.age_bat, s.age_pit_legacy, s.age_bat_legacy,
  s.n_thruorder_pitcher, s.n_priorpa_thisgame_player_at_bat,
  s.pitcher_days_since_prev_game, s.batter_days_since_prev_game,
  s.pitcher_days_until_next_game, s.batter_days_until_next_game,
  s.umpire, s.sv_id,
  s.season, s.game_date
)
