INSERT INTO silver_pitches (
  game_pk, at_bat_number, pitch_number,
  game_type, game_year, home_team, away_team, inning, inning_topbot,
  outs_when_up, balls, strikes,
  batter, pitcher, player_name, stand, p_throws,
  on_1b, on_2b, on_3b,
  fielder_2, fielder_3, fielder_4, fielder_5, fielder_6, fielder_7, fielder_8, fielder_9,
  pitch_type, pitch_name, type, events, description, des, zone, hit_location, bb_type,
  release_speed, effective_speed, release_spin_rate, spin_dir, spin_axis,
  release_pos_x, release_pos_y, release_pos_z, release_extension,
  pfx_x, pfx_z, plate_x, plate_z,
  vx0, vy0, vz0, ax, ay, az,
  sz_top, sz_bot,
  api_break_z_with_gravity, api_break_x_arm, api_break_x_batter_in, arm_angle,
  launch_speed, launch_angle, launch_speed_angle, hit_distance_sc,
  hc_x, hc_y, bat_speed, swing_length, hyper_speed,
  attack_angle, attack_direction, swing_path_tilt,
  intercept_ball_minus_batter_pos_x_inches, intercept_ball_minus_batter_pos_y_inches,
  home_score, away_score, bat_score, fld_score,
  post_home_score, post_away_score, post_bat_score, post_fld_score,
  home_score_diff, bat_score_diff,
  estimated_ba_using_speedangle, estimated_woba_using_speedangle, estimated_slg_using_speedangle,
  woba_value, woba_denom, babip_value, iso_value,
  home_win_exp, bat_win_exp, delta_home_win_exp, delta_run_exp, delta_pitcher_run_exp,
  if_fielding_alignment, of_fielding_alignment,
  age_pit, age_bat, age_pit_legacy, age_bat_legacy,
  n_thruorder_pitcher, n_priorpa_thisgame_player_at_bat,
  pitcher_days_since_prev_game, batter_days_since_prev_game,
  pitcher_days_until_next_game, batter_days_until_next_game,
  umpire, sv_id,
  season, game_date
)
SELECT
  game_pk, at_bat_number, pitch_number,
  game_type, game_year, home_team, away_team, inning, inning_topbot,
  outs_when_up, balls, strikes,
  batter, pitcher, player_name, stand, p_throws,
  on_1b, on_2b, on_3b,
  fielder_2, fielder_3, fielder_4, fielder_5, fielder_6, fielder_7, fielder_8, fielder_9,
  pitch_type, pitch_name, type, events, description, des, zone, hit_location, bb_type,
  release_speed, effective_speed, release_spin_rate, spin_dir, spin_axis,
  release_pos_x, release_pos_y, release_pos_z, release_extension,
  pfx_x, pfx_z, plate_x, plate_z,
  vx0, vy0, vz0, ax, ay, az,
  sz_top, sz_bot,
  api_break_z_with_gravity, api_break_x_arm, api_break_x_batter_in, arm_angle,
  launch_speed, launch_angle, launch_speed_angle, hit_distance_sc,
  hc_x, hc_y, bat_speed, swing_length, hyper_speed,
  attack_angle, attack_direction, swing_path_tilt,
  intercept_ball_minus_batter_pos_x_inches, intercept_ball_minus_batter_pos_y_inches,
  home_score, away_score, bat_score, fld_score,
  post_home_score, post_away_score, post_bat_score, post_fld_score,
  home_score_diff, bat_score_diff,
  estimated_ba_using_speedangle, estimated_woba_using_speedangle, estimated_slg_using_speedangle,
  woba_value, woba_denom, babip_value, iso_value,
  home_win_exp, bat_win_exp, delta_home_win_exp, delta_run_exp, delta_pitcher_run_exp,
  if_fielding_alignment, of_fielding_alignment,
  age_pit, age_bat, age_pit_legacy, age_bat_legacy,
  n_thruorder_pitcher, n_priorpa_thisgame_player_at_bat,
  pitcher_days_since_prev_game, batter_days_since_prev_game,
  pitcher_days_until_next_game, batter_days_until_next_game,
  umpire, sv_id,
  season, game_date
FROM silver_pitches_staging
WHERE season = {season}
  AND game_date = DATE '{game_date}'
  AND run_id = '{run_id}'
