project               = "doubleday"
environment           = "dev"
region                = "us-east-1"
athena_results_bucket = "appleforge-athena-query-results"
powertools_layer_arn  = "arn:aws:lambda:us-east-1:017000801446:layer:AWSLambdaPowertoolsPythonV3-python312-x86_64:15"
api_domain_name       = "api.doubleday-dev.appleforge.com"
frontend_domain_name  = "doubleday-dev.appleforge.com"
hosted_zone_name      = "appleforge.com"
cognito_callback_urls = ["http://localhost:8081/callback", "https://doubleday-dev.appleforge.com/callback", "doubleday://callback"]
cognito_logout_urls   = ["http://localhost:8081", "https://doubleday-dev.appleforge.com", "doubleday://"]
stripe_price_id       = "price_1T6H6GPsWrWHXBNRvzYIqiev"
